name: Deployment Pipeline

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3.5.1
        with:
          node-version: "14"
      - name: Install dependencies
        run: npm install --no-audit --no-fund --no-optional
        
        uses: appleboy/scp-action@master
        with:
          host: ${{ HOST_SECRET }}
          username: ${{ USERNAME_SECRET }}
          key_path: "AKIA5YWIXALBZKEVB7EF"
          source: "rutbackSand.zip"
          target: "~/artifacts"
      - name: Unzip the build
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ HOST_SECRET }}
          username: ${{ USERNAME_SECRET }}
          key_path: "AKIA5YWIXALBZKEVB7EF"
          script_stop: true
          script: bash  ~/scripts/autodeployrutback-sandbox.sh