name: pipeline_Prueba
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check out proyect
      - name: Run a one-line script
        run: echo Hello, world 2!
      - name: Run a multi-line script
        run: |
          - echo Hola este es mi primer pipeline,
          - time
          - touch hola.txt
          - ls -la
